env: local
app:
  ip: "0.0.0.0"
  port: 8080
  read_timeout: 4s
  write_timeout: 4s
  idle_timeout": 60s
  lots:
    - RUB
    - BTC
    - ETH
    - USDT
    - USDC
    - SOL
    - DOGE
  token_length: 32
database:
  ip: jacutesql
  port: 7432
